import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavItem from "@/components/ui/nav-item";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center`}
      >
        <div className="flex flex-col items-center w-[375px] h-[812px] max-h-screen bg-surface-default">
          <div className="flex-1 w-[344px] flex flex-col gap-y-6 overflow-">
            {children}
          </div>
          <div className="flex w-full px-[16px] pt-[8px] pb-[16px] bg-surface-light opacity-80">
            <NavItem className="flex-1" />
            <NavItem className="flex-1" />
            <NavItem className="flex-1" />
            <NavItem className="flex-1" />
          </div>
        </div>
      </body>
    </html>
  );
}
